ENV: "{ENV:development}"
HTTP:
  Port: "{HTTP_PORT:8080}"
  Greetings: "{HTTP_GREETINGS:hello there}"
Database:
  Host: "{DB_HOST:localhost}"
  Port: "{DB_PORT:5432}"
  User: "{DB_USER:admin}"
  DbName: "{DB_NAME:transactionsdb}"
  Password: "{DB_PASSWORD:admin}"